name: Build macOs Executable with py2app

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with: 
          python-version: 3.19
      
      - name: Install py2app and dependencies
        run: | 
          python -m pip install --upgrade pip
          pip install py2app
          pip install tkinter
          pip install PIL
          pip install yt_dlp

      - name: Build macOS app with py2app
        run: |
          python setup.py py2app
      
      - name: List build outputs
        run: ls dist/

      - name: Upload app to artifacts
        uses: actions/upload-artifact@v2
        with:
          name: macos-app
          path: dist/
